# Generated by Django 2.0.1 on 2018-03-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('QQnumber', models.CharField(max_length=20, unique=True)),
                ('QQname', models.CharField(max_length=20)),
                ('isbinding', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['userid'],
            },
        ),
    ]
