# Generated by Django 2.0.1 on 2018-03-21 02:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_auto_20180320_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('schoolYear', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('credit', models.FloatField()),
                ('intstartSection', models.IntegerField()),
                ('endSection', models.IntegerField()),
                ('startWeek', models.IntegerField()),
                ('endWeek', models.IntegerField()),
                ('dayOfWeek', models.IntegerField()),
                ('classroom', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.User')),
            ],
            options={
                'db_table': 'course',
                'ordering': ['cid'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
