# Generated by Django 2.0.1 on 2018-03-30 12:21

import appuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0004_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.FileField(upload_to=appuser.models.user_directory_path),
        ),
    ]
